name: Test and Deploy

on:
  push:
    branches:
      - main
jobs:
  test-utils:
    name: Test Utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test Utils
        run: npm run test-utils

  test-app:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone
        uses: actions/checkout@v2.4.2
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: test_db
          postgresql user: test_user
          postgresql password: password
      - name: Install dependencies
        run: npm install
      - name: Test App
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=password npm run test-app

  deploy:
    name: Deploy
    needs: [test-utils, test-app]
    runs-on: ubuntu-latest
    steps:
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
